version: '3.9'

volumes:
  db_volume:

services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    restart: always
